base_log_path = "./test_logs"
lingo_api_url = "https://api.lingo.dev/process"
lingo_api_key = "api_i5o7fvkedtg3pf2q2m1voovo"
loki_url = "http://localhost:3100/loki/api/v1/push"
target_language = "es"

