base_log_path = "./test_logs"
lingo_api_url = "https://api.lingo.dev/process"
lingo_api_key = ""
loki_url = "http://localhost:3100/loki/api/v1/push"
target_language = "es"
exclude_namespaces = "kube-system,kubernetes-dashboard,default"

