apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lingo-observer
  labels:
    app: lingo-observer
spec:
  selector:
    matchLabels:
      name: lingo-observer
  template:
    metadata:
      labels:
        name: lingo-observer
    spec:
      containers:
      - name: lingo-observer
        image: lastpatriot/lingo-observer:v1
        imagePullPolicy: Always
        env:
        - name: EXCLUDE_NAMESPACES
          value: "kube-system,kubernetes-dashboard,default"
        securityContext:
          privileged: true
        workingDir: /etc/lingo-observer
        volumeMounts:
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /etc/lingo-observer
      volumes:
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: lingo-observer-config
