apiVersion: v1
kind: ConfigMap
metadata:
  name: lingo-observer-config
  namespace: default
data:
  config.toml: |
    base_log_path = "/var/log/pods"
    lingo_api_url = "https://api.lingo.dev/process"
    lingo_api_key = "lingo_sk_RCdtsQ4G7yGM6T9YwjO7UyytdY8_52yN9eZ5zR6TBdc"
    loki_url = "http://loki-stack:3100/loki/api/v1/push"
    target_language = "es"
